version: '3.9'
name: "lh-nextjs-auth"

networks:
  automation:
    name: automation
  node-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - "C:\\VMs\\DockerVolumes\\pg-tmp:/var/lib/postgresql/data/"
    ports:
      - 54433:5432
